name: "PreProcess3D"

base_dir : "/drive/dumps/multimodal-spaces"
exp_dir  : ""
  
data:
  sources: []
  process_dir: ${base_dir}/preprocess_feats
  Scannet:
    base_dir         : /drive/datasets/Scannet
    shape_dir        : /drive/datasets/Shapenet/ShapeNetCore.v2
    process_dir      : ${data.process_dir}/Scannet
    chunked_dir      : ${data.process_dir}/objects_chunked/Scannet
    processor3D      : Scannet3DProcessor
    mesh_subfix      : _vh_clean_2.labels.ply
    seg_subfix       : _vh_clean_2.0.010000.segs.json
    aggre_subfix     : _vh_clean.aggregation.json
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
  
  Scan3R:
    base_dir         : /drive/datasets/Scan3R
    process_dir      : ${data.process_dir}/Scan3R
    chunked_dir      : ${data.process_dir}/objects_chunked/Scan3R
    processor3D      : Scan3R3DProcessor
    processor2D      : Scan3R2DProcessor
    processor1D      : Scan3R1DProcessor
    label_filename   : labels.instances.align.annotated.v2.ply
    skip_frames      : 1
    avail_modalities : ['point', 'rgb', 'referral']
  
  Front3D:
    base_dir       : /drive/datasets/3D-Front-rendered
    process_dir    : ${data.process_dir}/Front3D
    chunked_dir    : ${data.process_dir}/objects_chunked/Front3D
    processor3D    : FrontD3DProcessor
    processor2D    : FrontD2DProcessor
    max_object_len : 80
    voxel_size     : 0.02
    avail_modalities : ['point', 'rgb', 'referral']

  Shapenet:
    base_dir       : /drive/datasets/Shapenet/ShapeNetCore.v2

modality_info:
  1D  :
    feature_extractor: 
      model     : LongCLIP
      ckpt      : /drive/pretrained-models/longclip-L.pt
      embed_dim : 768
  
  2D  :
    feature_extractor:
      model     : DinoV2
      ckpt      : dinov2_vitg14
      embed_dim : 1536
  
  3D  :
    feature_extractor:
      model      : I2PMAE
      ckpt       : /drive/pretrained-models/pointbind_i2pmae.pt 
      embed_dim  : 384
    
    voxel_size : 0.05
    max_points_per_object : 1024
    min_points_per_object : 50

# 'Preprocess', 'PreprocessMultimodal' 'ObjectLevelTrain', 'SceneLevelTrain', 'UnifiedTrain1D', 'UnifiedTrain2D', 'UnifiedTrain3D'
task: 
  name       : PreprocessMultimodal 
  Preprocess :
    modality : '3D'
    splits   : ['train', 'val']
  
  PreprocessMultimodal :
    processor : MultimodalPreprocessor
    splits    : ['train', 'val']